### PR TITLE
fix(index.ts): make sure a package.json is always there

### PR DESCRIPTION
**Pull request by Badisi**
Fix a regression introduced in #15

### CODE REVIEW

**Comment by Badisi** [comment]
I'm not sure why it is failing...

And seems like it was also failing before but silently:
https://github.com/webdriverio/create-wdio/runs/4090272802?check_suite_focus=true#step:6:33

**Comment by christian-bromann** [comment]
Can we bump some of the unit tests coverage?

**Comment by christian-bromann** [comment]
You are right, the coverage is not brilliant anyway. This patch should not suffer from that. I will merge and tweak in `main` branch.

**Review by christian-bromann — APPROVED** [review]
Thanks 👍

**Pull request merged**
